services:
  bot:
    container_name: minatovar_bot
    build: ./src
    restart: always
    volumes:
      - ./data:/data
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    expose:
      - 6379
    environment:
      - REDIS_PASSWORD=2007Fj2007
      - REDIS_USER=minatovar
      - REDIS_USER_PASSWORD=2007Fj2007
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass 2007Fj2007" >> /usr/local/etc/redis/redis.conf &&
        echo appendfilename "appendonly.aof" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync always" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user minatovar on >2007Fj2007 ~* +@all" >> /usr/local/etc/redis/users.acl &&
        echo "save 100 1" >> /usr/local/etc/redis/redis.conf &&
        echo "auto-aof-rewrite-min-size 64mb" >> /usr/local/etc/redis/redis.conf &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl  
      '
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "2007Fj2007", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  redis_data:
