services:
  bot:
    container_name: bot
    build: ./src
    restart: always
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    expose:
      - 6379
    environment:
      - REDIS_PASSWORD=2007Fj2007
      - REDIS_USER=minatovar
      - REDIS_USER_PASSWORD=2007Fj2007
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass 2007Fj2007" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user minatovar on >2007Fj2007 ~* +@all" >> /usr/local/etc/redis/users.acl &&
        echo "save 900 1" >> /usr/local/etc/redis/redis.conf &&
<<<<<<< HEAD
=======
        echo "auto-aof-rewrite-min-size 64mb" >> /usr/local/etc/redis/redis.conf &&
>>>>>>> 30accf88c2b922458a3609f3e45182ba5123b235
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
        
      '

volumes:
  redis_data:
