services:
  bot:
    container_name: bot
    build: ./src
    restart: always
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    expose:
      - 6379
    command: ["redis-server", "--appendonly", "yes", "--save", "3600 1"]

volumes:
  redis_data:
