services:
  bot:
    container_name: bot
    build: ./src
    restart: always
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    expose:
      - 6379
    
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
    redis_data:
