# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "migrations",
    "Dockerfile",
    "docker",
    "*.ini",
    "*.txt",
    "*.http",
    "__init__.py",
    "alembic"
]

line-length = 88
indent-width = 4

lint.fixable = ["ALL"]

target-version = "py39"

[format]
quote-style = "double"
indent-style = "tab"
