"""rename url to article

Revision ID: 20d34876f698
Revises: e024bb7ee40a
Create Date: 2025-01-21 20:25:12.680392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d34876f698'
down_revision: Union[str, None] = 'e024bb7ee40a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('arcticle', sa.String(length=255), nullable=False))
    op.drop_column('orders', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('orders', 'arcticle')
    # ### end Alembic commands ###
