"""promos text 4096

Revision ID: 2f0b0d6e58d4
Revises: 48e209a3c16a
Create Date: 2025-01-15 16:55:54.490530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0b0d6e58d4'
down_revision: Union[str, None] = '48e209a3c16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promos', 'descriptions',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=4096),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promos', 'descriptions',
               existing_type=sa.String(length=4096),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
