"""add admin foreign key

Revision ID: 63e9ed217af6
Revises: 98c53d114243
Create Date: 2025-08-31 15:29:56.304213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e9ed217af6'
down_revision: Union[str, None] = '98c53d114243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('tg_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('admins_tg_id_fkey'), 'admins', 'users', ['tg_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('admins_tg_id_fkey'), 'admins', type_='foreignkey')
    op.drop_column('admins', 'tg_id')
    # ### end Alembic commands ###
