"""rename fix

Revision ID: 7f4dcf7d43ea
Revises: 20d34876f698
Create Date: 2025-01-21 20:29:37.877949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4dcf7d43ea'
down_revision: Union[str, None] = '20d34876f698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('article', sa.String(length=255), nullable=False))
    op.drop_column('orders', 'arcticle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('arcticle', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('orders', 'article')
    # ### end Alembic commands ###
