"""create new base model

Revision ID: 94ee2181f8f3
Revises: f0dbb67824ea
Create Date: 2025-07-14 16:59:21.360437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ee2181f8f3'
down_revision: Union[str, None] = 'f0dbb67824ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('time_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('promos', sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('promos', sa.Column('time_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('referrals', sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('referrals', sa.Column('time_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('settings', sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('settings', sa.Column('time_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('time_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time_updated')
    op.drop_column('users', 'time_created')
    op.drop_column('settings', 'time_updated')
    op.drop_column('settings', 'time_created')
    op.drop_column('referrals', 'time_updated')
    op.drop_column('referrals', 'time_created')
    op.drop_column('promos', 'time_updated')
    op.drop_column('promos', 'time_created')
    op.drop_column('orders', 'time_updated')
    # ### end Alembic commands ###
