"""cascade_on_delete_in__referral

Revision ID: b8d434532ce5
Revises: 2f0b0d6e58d4
Create Date: 2025-01-19 19:57:52.176771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d434532ce5'
down_revision: Union[str, None] = '2f0b0d6e58d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('referrals_id_to_fkey', 'referrals', type_='foreignkey')
    op.drop_constraint('referrals_id_from_fkey', 'referrals', type_='foreignkey')
    op.create_foreign_key(None, 'referrals', 'users', ['id_to'], ['user_id'], ondelete='cascade')
    op.create_foreign_key(None, 'referrals', 'users', ['id_from'], ['user_id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.create_foreign_key('referrals_id_from_fkey', 'referrals', 'users', ['id_from'], ['user_id'])
    op.create_foreign_key('referrals_id_to_fkey', 'referrals', 'users', ['id_to'], ['user_id'])
    # ### end Alembic commands ###
