"""create

Revision ID: c9c2c47ccd99
Revises: 
Create Date: 2025-02-07 21:28:27.625969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c2c47ccd99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descriptions', sa.String(length=4096), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PAID', 'BOUGHT_OUT', 'AGENT', 'CUSTOMS', 'MOSCOW_WAREHOUSE', 'TO_PETERSBURG', 'TO_CUSTOMER_CITY', 'COMPLETED', 'CANCELED', name='orderstatus'), nullable=False),
    sa.Column('article', sa.String(length=255), nullable=False),
    sa.Column('addres', sa.String(length=255), nullable=False),
    sa.Column('price_rub', sa.Float(), nullable=False),
    sa.Column('price_cny', sa.Integer(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('type_item', sa.Enum('SHOES', 'CLOTH', name='ordertypeitem'), nullable=False),
    sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_from', sa.BIGINT(), nullable=False),
    sa.Column('id_to', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['id_from'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_to'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_from', 'id_to', name='unique_referral'),
    sa.UniqueConstraint('id_to')
    )
    op.create_index('ix_user_id', 'referrals', ['id_from', 'id_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_id', table_name='referrals')
    op.drop_table('referrals')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('promos')
    # ### end Alembic commands ###
