"""cascade_on_delete_in__referral

Revision ID: e024bb7ee40a
Revises: b8d434532ce5
Create Date: 2025-01-19 21:28:17.762377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e024bb7ee40a'
down_revision: Union[str, None] = 'b8d434532ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
