import os

from dotenv import load_dotenv

load_dotenv()
DEBUG = os.getenv("DEBUG") == "True"
TOKEN = os.getenv("TEST_TOKEN") if DEBUG else os.getenv("TOKEN")
HOST = os.getenv("HOST")
PORT = int(os.getenv("PORT"))
WEBHOOK_PATH = '/webhook'
BASE_URL = os.getenv("BASE_URL")

REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_DB = os.getenv("REDIS_DB")
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")
REDIS_USER = os.getenv("REDIS_USER")

DATA_FILE = os.getenv("DATA_FILE")
STATIC_FILES = os.getenv("STATIC_FILES")
MEDIA_FILES = f"{STATIC_FILES}/media"
TEMPLATE_DIR = os.getenv("TEMPLATE_DIR")

POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_NAME = os.getenv("POSTGRES_NAME")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")

ADMIN_GROUP_ID = os.getenv("ADMIN_GROUP_ID")
ADMINS = (1019030670, 1324716819, 1423930901)
LOG_ADMIN = 1324716819

REAL_DATABASE_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_NAME}"
ALEMBIC_DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_NAME}"
